<?php
	// Message content. 
	$msj = "Sent from your personal website.\n";
	$msj.= "\nWritten by ". $_POST['name'] ." (".$_POST['tel']." | ".$_POST['email'].") \n";
	$msj.= "\n---------------------\n";
	$msj.= $_POST['msj'];
	$msj.= "\n---------------------\n";
	$msj.= "This is an autogenerated message. Do not reply.";

	// Headers. 
	$to = "Fermoto5HD@outlook.com";
	$remitente = $_POST['email'];
	$subject = "[Personal WebSite] ".$_POST['name']." sent you a message";
	mail($to,$subject,$msj, "From: $remitente");

	// Return success message. 
	echo "¡Message sent!";
?>